import datetime as dt

mock_users = [
    {
        "username": "demo", 
        "first_name": "",
        "last_name": "",
        "role": "admin", 
        "password": "demo"
    },

    {
        "username": "director", 
        "first_name": "",
        "last_name": "",
        "role": "director", 
        "password": "director"
    },
    {
        "username": "abbyburton", 
        "first_name": "Abby",
        "last_name": "Burton",
        "role": "director", 
        "password": "abbyburton"
    },

    {
        "username": "john", 
        "first_name": "John",
        "last_name": "Doe",
        "role": "manager", 
        "password": "john"
    },
    {
        "username": "mary", 
        "first_name": "Mary",
        "last_name": "Strawberry",
        "role": "manager", 
        "password": "mary"
    },
    {
        "username": "zachwalter", 
        "first_name": "Zach",
        "last_name": "Walter",
        "role": "manager", 
        "password": "zachwalter"
    },

    {
        "username": "marsolis", 
        "first_name": "Marjorie",
        "last_name": "Solis",
        "role": "manager", 
        "password": "marsolis"
    },
    {
        "username": "markhebert", 
        "first_name": "Mark",
        "last_name": "Hebert",
        "role": "manager", 
        "password": "markhebert"
    },

    {
        "username": "jandrews", 
        "first_name": "James",
        "last_name": "Andrews",
        "role": "staff", 
        "password": "jandrews"
    },
    {
        "username": "jgriffith", 
        "first_name": "Jason",
        "last_name": "Griffith",
        "role": "staff", 
        "password": "jgriffith"
    },
    {
        "username": "crussell", 
        "first_name": "Cameron",
        "last_name": "Russell",
        "role": "staff",
        "password": "crussell"
    },
]

mock_notifications = [
    {
        "sender": "demo",
        "recipient": "john",
        "notification_send_date": dt.date.today(),
        "notification_head": "Help! AED is flashing red light", 
        "notification_body": "AED was being used for ... and when I ... the AED ...",
    },
    {
        "sender": "demo",
        "recipient": "mary",
        "notification_send_date": dt.date.today(),
        "notification_head": "Help! AED is flashing red light", 
        "notification_body": "AED was being used for ... and when I ... the AED ...",
    },
    {
        "sender": "demo",
        "recipient": "zachwalter",
        "notification_send_date": dt.date.today(),
        "notification_head": "Help! AED is flashing red light", 
        "notification_body": "AED was being used for ... and when I ... the AED ...",
    },
    {
        "sender": "demo",
        "recipient": "marsolis",
        "notification_send_date": dt.date.today(),
        "notification_head": "Help! AED is flashing red light", 
        "notification_body": "AED was being used for ... and when I ... the AED ...",
    },
    {
        "sender": "demo",
        "recipient": "markhebert",
        "notification_send_date": dt.date.today(),
        "notification_head": "Help! AED is flashing red light", 
        "notification_body": "AED was being used for ... and when I ... the AED ...",
    },
    {
        "sender": "Nurse Magda",
        "recipient": "john",
        "notification_send_date": dt.date.today(),
        "notification_head": "X-ray scanner is making a weird noise", 
        "notification_body": "When working with a patient, the scanner started making a deep grumble sound.",
    },
]

mock_assets = [
    {
        "serial_number": "0001",
        "device_name": "CardiGuard 3000",
        "brand": "HeartSafe",
        "generic_name": "Automated External Defibrillator (AED)",
        "manufacturer": "",
        "department_location": "",
        "average_use_per_year": "500 uses",
        "total_units_in_service": 20000,
        "failure_incidents_in_past_year": 50,
        "total_failures_in_history": 200,
        "last_maintenance_date": dt.date(2025, 1, 1),
        "total_maintenance_activities_in_past_year": 150,
        "maintenance_type": "Battery replacement and calibration",
        "cost_per_maintenance_activity": 50.00,
        "total_maintenance_costs_in_past_year": 7500.00,
        "upcoming_maintenance_action_date": dt.date.today() + dt.timedelta(days=2),
    },
    {
        "serial_number": "0010",
        "device_name": "BioVent Pro",
        "brand": "AirHealth",
        "generic_name": "Mechanical Ventilator",
        "manufacturer": "RespiraTech Ltd.",
        "department_location": "",
        "average_use_per_year": "100000 hours",
        "total_units_in_service": 5000,
        "failure_incidents_in_past_year": 15,
        "total_failures_in_history": 80,
        "last_maintenance_date": dt.date(2025, 1, 1),
        "total_maintenance_activities_in_past_year": 300,
        "maintenance_type": "Circuit board inspection and cleaning",
        "cost_per_maintenance_activity": 120.00,
        "total_maintenance_costs_in_past_year": 36000.00,
        "upcoming_maintenance_action_date": dt.date.today() + dt.timedelta(days=4),
    },
    {
        "serial_number": "0011",
        "device_name": "SafePulse Infusion Pump",
        "brand": "MedFusion",
        "generic_name": "Infusion Pump",
        "manufacturer": "HealthTech Innovations",
        "department_location": "",
        "average_use_per_year": "50000 hours",
        "total_units_in_service": 10000,
        "failure_incidents_in_past_year": 40,
        "total_failures_in_history": 250,
        "last_maintenance_date": dt.date(2025, 1, 1),
        "total_maintenance_activities_in_past_year": 500,
        "maintenance_type": "Pump motor inspection and replacement",
        "cost_per_maintenance_activity": 200.00,
        "total_maintenance_costs_in_past_year": 100000.00,
        "upcoming_maintenance_action_date": dt.date.today() + dt.timedelta(days=5),
    },
    {
        "serial_number": "0100",
        "device_name": "MediScope 4K",
        "brand": "ScopeVision",
        "generic_name": "Endoscope",
        "manufacturer": "MediScope Technologies",
        "department_location": "",
        "average_use_per_year": "200 uses",
        "total_units_in_service": 12000,
        "failure_incidents_in_past_year": 90,
        "total_failures_in_history": 350,
        "last_maintenance_date": dt.date(2025, 1, 1),
        "total_maintenance_activities_in_past_year": 600,
        "maintenance_type": "Lens cleaning and inspection",
        "cost_per_maintenance_activity": 75.00,
        "total_maintenance_costs_in_past_year": 45000.00,
        "upcoming_maintenance_action_date": dt.date.today() + dt.timedelta(days=8),
    },
    {
        "serial_number": "0101",
        "device_name": "GlucoTrack 1000",
        "brand": "HealthGlobe",
        "generic_name": "Continuous Glucose Monitor (CGM)",
        "manufacturer": "Diabetech Industries",
        "department_location": "Emergeny",
        "average_use_per_year": "300000 sensor readings",
        "total_units_in_service": 50000,
        "failure_incidents_in_past_year": 1000,
        "total_failures_in_history": 2500,
        "last_maintenance_date": dt.date(2025, 1, 1),
        "total_maintenance_activities_in_past_year": 1200,
        "maintenance_type": "Sensor replacement and calibration",
        "cost_per_maintenance_activity": 30.00,
        "total_maintenance_costs_in_past_year": 36000.00,
        "upcoming_maintenance_action_date": dt.date.today() + dt.timedelta(days=12),
    },
    {
        "serial_number": "0110",
        "device_name": "NeoPulse ECG Monitor",
        "brand": "PulseMed",
        "generic_name": "Electrocardiogram (ECG)",
        "manufacturer": "CardioCare Solutions",
        "department_location": "",
        "average_use_per_year": "75000 hours",
        "total_units_in_service": 25000,
        "failure_incidents_in_past_year": 175,
        "total_failures_in_history": 1000,
        "last_maintenance_date": dt.date(2025, 1, 1),
        "total_maintenance_activities_in_past_year": 500,
        "maintenance_type": "Lead inspection and cleaning",
        "cost_per_maintenance_activity": 50.00,
        "total_maintenance_costs_in_past_year": 25000.00,
        "upcoming_maintenance_action_date": dt.date.today() + dt.timedelta(days=13),
    },
    {
        "serial_number": "0111",
        "device_name": "SurgiLaser Pro",
        "brand": "LaserTech",
        "generic_name": "Laser Surgical System",
        "manufacturer": "OptiSurgical Inc.",
        "department_location": "",
        "average_use_per_year": "1000 hours",
        "total_units_in_service": 3000,
        "failure_incidents_in_past_year": 30,
        "total_failures_in_history": 150,
        "last_maintenance_date": dt.date(2025, 1, 1),
        "total_maintenance_activities_in_past_year": 100,
        "maintenance_type": "Laser calibration and alignment",
        "cost_per_maintenance_activity": 500.00,
        "total_maintenance_costs_in_past_year": 50000.00,
        "upcoming_maintenance_action_date": dt.date.today() + dt.timedelta(days=6),
    },
    {
        "serial_number": "1000",
        "device_name": "DermalScan X-ray",
        "brand": "DermTech",
        "generic_name": "X-ray Imaging System",
        "manufacturer": "RadMed Industries",
        "department_location": "",
        "average_use_per_year": "50000 images",
        "total_units_in_service": 2000,
        "failure_incidents_in_past_year": 18,
        "total_failures_in_history": 100,
        "last_maintenance_date": dt.date(2025, 1, 1),
        "total_maintenance_activities_in_past_year": 150,
        "maintenance_type": "Radiation sensor inspection and recalibration",
        "cost_per_maintenance_activity": 150.00,
        "total_maintenance_costs_in_past_year": 22500.00,
        "upcoming_maintenance_action_date": dt.date.today() + dt.timedelta(days=14),
    },
    {
        "serial_number": "1001",
        "device_name": "NephroClean Dialysis Machine",
        "brand": "LifePure",
        "generic_name": "Hemodialysis Machine",
        "manufacturer": "NephroCare Medical",
        "department_location": "",
        "average_use_per_year": "40000 dialysis sessions",
        "total_units_in_service": 8000,
        "failure_incidents_in_past_year": 112,
        "total_failures_in_history": 400,
        "last_maintenance_date": dt.date(2025, 1, 1),
        "total_maintenance_activities_in_past_year": 1000,
        "maintenance_type": "Fluid pump inspection and replacement",
        "cost_per_maintenance_activity": 300.00,
        "total_maintenance_costs_in_past_year": 300000.00,
        "upcoming_maintenance_action_date": dt.date.today() + dt.timedelta(days=22),
    },
    {
        "serial_number": "1010",
        "device_name": "VisionPlus Retinal Scanner",
        "brand": "EyeTech",
        "generic_name": "Optical Coherence Tomography (OCT) Scanner",
        "manufacturer": "Visionary Medical Devices",
        "department_location": "",
        "average_use_per_year": "25000 scans",
        "total_units_in_service": 3500,
        "failure_incidents_in_past_year": 21,
        "total_failures_in_history": 150,
        "last_maintenance_date": dt.date(2025, 1, 1),
        "total_maintenance_activities_in_past_year": 180,
        "maintenance_type": "Sensor recalibration and lens cleaning",
        "cost_per_maintenance_activity": 250.00,
        "total_maintenance_costs_in_past_year": 45000.00,
        "upcoming_maintenance_action_date": dt.date.today() + dt.timedelta(days=17),
    },
]





"""
    {
        "device_name": "",
        "brand": "",
        "generic_name": "",
        "manufacturer": "",
        "department_location": "",
        "average_use_per_year": "",
        "total_units_in_service": 0,
        "failure_incidents_in_past_year": 0,
        "total_failures_in_history": 0,
        "last_maintenance_date": dt.date(2025, 1, 1),
        "total_maintenance_activities_in_past_year": 0,
        "maintenance_type": "",
        "cost_per_maintenance_activity": 0.00,
        "total_maintenance_costs_in_past_year": 0.00,
    },
"""